sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t thebluealliance/gdcv ./ops/
  - docker run thebluealliance/gdcv /bin/sh -c "ls"
  - docker run thebluealliance/gdcv /bin/sh -c "ls /root"
  - docker run thebluealliance/gdcv /bin/sh -c "run-tests.sh"
